### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by nickiemc** [corgibytes/mendercon-com#23]
Change the default branch from `master` to `main`. See https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx for details.

**Comment by nickiemc** [comment]
Renamed `master` to `main` using GitHub's UI.

**Comment by nickiemc** [comment]
It looks like GitHub Pages still only support deploying from `gh-pages` or `master`.

**Comment by mscottford** [comment]
I've successfully adjusted the name of the primary branch to `main`.
