### ISSUE TITLE
Add descriptions to Schedule items

### ISSUE THREAD

**Issue by nickiemc** [corgibytes/mendercon-com#9]
The items on the Schedule page currently have TBD/Lorem Ipsum as their descriptions:

![image](https://user-images.githubusercontent.com/7128495/81570597-6cd3f980-9366-11ea-9f3b-2d195d02af13.png)

The descriptions should either be updated to be accurate or removed.

**Comment by ccarothers** [comment]
@nickiemc I'm not able to get to this issue (i.e. cannot find the screenshot you posted above), either in editing or preview modes. Do you think it was somehow resolved? I can't actually find anywhere to edit "descriptions" under each item in Schedule....

**Comment by nickiemc** [comment]
@ccarothers This is actually on mendercon.com, not Hopin. It sounds like maybe you were looking at Hopin? Given how close we are to Thursday, I think it's fine for us to just remove the descriptions. I can do that later tonight if that's easier for you.

**Comment by ccarothers** [comment]
@nickiemc ahh, got it. yes, was in Hopin. if you're able to delete them that would be excellent (thank you!!)

**Comment by nickiemc** [comment]
PR #15 is ready for review.

**Comment by mscottford** [comment]
We ended up just removing the descriptions, so this is done.
